/// Obtener todos los productos
GET https://apii-veterinaria-cande.onrender.com/productos

###


/// crear un producto
POST https://apii-veterinaria-cande.onrender.com/productos
Content-Type: application/json

{
  "codigo": "VET001",
  "nombre": "Alimento balanceado para perros adultos",
  "precio": 12500,
  "categoria": ["alimentos", "perros"]
}

###


/// obtener producto por código
GET https://apii-veterinaria-cande.onrender.com/productos/VET001

###


/// actualizar producto
PUT https://apii-veterinaria-cande.onrender.com/productos/VET001
Content-Type: application/json

{
  "precio": 13500
}

###


/// eliminar producto
DELETE https://apii-veterinaria-cande.onrender.com/productos/VET001
